# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 17:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[(b'draft', b'draft'), (b'waiting_for_launch', b'waiting_for_launch'), (b'launched', b'launched'), (b'under_review', b'under_review'), (b'closed', b'closed')], default=b'draft', max_length=255)),
                ('template', models.FileField(blank=True, null=True, upload_to=b'campaign')),
                ('forms', django.contrib.postgres.fields.jsonb.JSONField()),
                ('emails', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
